
fmod NUMBERS is
  sort Number .
  op 0 : -> Number [ctor] .
  op s : -> Number [ctor] .
  op __ : Number Number -> Number [ctor comm assoc id: 0 prec 10] .
endfm

fmod NUMBER-SETS is
  protecting NUMBERS .

  sort NumberSet NeNumberSet .
  subsort Number < NeNumberSet < NumberSet .
  op none : -> NumberSet [ctor] .
  op _;_ : NumberSet NumberSet -> NumberSet [ctor comm assoc id: none] .
  op _;_ : NeNumberSet NumberSet -> NeNumberSet [ctor comm assoc id: none] .
  op _;_ : NumberSet NeNumberSet -> NeNumberSet [ctor comm assoc id: none] .
endfm

fmod NUMBER-MAX is
  protecting NUMBER-SETS .

  vars N M : Number . var NS : NumberSet .

  op max : NeNumberSet -> Number .
  eq max(N ; N M ; NS) = max(N M ; NS) [variant] .
  eq max(N) = N [variant] .
endfm
