set protect BOOL off .

mod TEST1 is
  sorts Bool Proc ProcSet Status .
  subsort Proc < ProcSet .
  op true : -> Bool [ctor] .
  op _and_ : Bool Bool -> Bool [assoc comm] .
  op _or_ : Bool Bool -> Bool [assoc comm] .
  op <_> : Status -> Proc [ctor] .
  op none : -> ProcSet [ctor] .
  op __ : ProcSet ProcSet -> ProcSet [assoc comm ctor id: none] .
  op initialCond : ProcSet -> Bool [ctor] .
endm

unify initialCond(P:ProcSet < S:Status >) and (true or true) =? B:Bool .

